apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ing
  namespace: ns02
  labels:
    environment: production
    name: my-app-ing
spec:
  rules:
  - host: my-app.sith.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-svc
            port:
              number: 80
